language: python
python:
  - "2.7"
install:
  - "pip install -r requirements.txt --use-mirrors"
  # doesn't work, returns with 100, don't know why
  # - "sudo apt-get install google-chrome-stable"
env:
  - DB=mysql
before_script:
  - bash main/travis/setup.sh
  - mysql -e 'create database class2go'
script: 
  # for now don't run selenium tests until we can figure out how 
  - cd main; python manage.py test -v 2 --attr='!selenium'
notifications:
  irc: "irc.freenode.org#class2go-internal"
